[tool.poetry]
name = "artistic-intelligence-data"
version = "0.1.0"
description = "Data collector, query API and more to create digital art."
homepage = "https://artisticintelligence.nl"
repository = "https://github.com/robinklaassen/artistic-intelligence-data"
authors = ["Robin Klaassen <info@robinklaassen.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [{include = "artistic_intelligence_data"}]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
pydantic = "^2.7.0"
psycopg2 = "^2.9.9"
structlog = "^24.1.0"
APScheduler = "^3.10.4"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
ruff = "^0.4.1"
mypy = "^1.9.0"
types-psycopg2 = "^2.9.21.20240417"
types-requests = "^2.31.0.20240406"
scons = "^4.7.0"
bandit = "^1.7.8"

[tool.poetry.scripts]
artistic-intelligence-data = "artistic_intelligence_data.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.mypy]
ignore_missing_imports = true
