# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: push

env:
  PYTHON_VERSION: "3.12"

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Lint
        run: scons lint
      - name: Lock
        run: scons lock
      - name: Type
        run: scons type
      - name: Test
        run: scons test
      - name: Sec
        run: scons sec

  CD:
    runs-on: ubuntu-latest
    needs: CI
    if: github.ref == 'refs/heads/main'  # expression strings must be single quoted
    steps:
      - name: Deploy app
        run: exit 0  # TODO